site_name: Postweb相关资料
nav:
    - 1、系统开发手册:
      - 1.1 基础理论.md
      - 1.2 初步动手实践.md
      - 1.3 Torchserve使用.md
      - 1.4 如何添加接口.md
    - 2、系统部署手册:
      - 2.1 系统部署相关知识.md
      - 2.2 系统部署手册.md
    - 3、系统使用手册:
        - 3.1 模型添加说明.md
theme:
  name: 'material'